const countries = [
    { key: "Argentina", ISO: "ar" },
    { key: "Austria", ISO: "at" },
    { key: "Australia", ISO: "au" },
    { key: "Belgium", ISO: "be" },
    { key: "Bulgaria", ISO: "bg" },
    { key: "Brazil", ISO: "br" },
    { key: "Canada", ISO: "ca" },
    { key: "Switzerland", ISO: "ch" },
    { key: "China", ISO: "cn" },
    { key: "Colombia", ISO: "co" },
    { key: "Cuba", ISO: "cu" },
    { key: "Czech Republic", ISO: "cz" },
    { key: "Germany", ISO: "de" },
    { key: "Egypt", ISO: "eg" },
    { key: "France", ISO: "fr" },
    { key: "United Kingdom", ISO: "gb" },
    { key: "Greece", ISO: "gr" },
    { key: "Hong Kong", ISO: "hk" },
    { key: "Hungary", ISO: "hu" },
    { key: "Indonesia", ISO: "id" },
    { key: "Ireland", ISO: "ie" },
    { key: "Israel", ISO: "il" },
    { key: "India", ISO: "in" },
    { key: "Italy", ISO: "it" },
    { key: "Japan", ISO: "jp" },
    { key: "South Korea", ISO: "kr" },
    { key: "Lithuania", ISO: "lt" },
    { key: "Latvia", ISO: "lv" },
    { key: "Mexico", ISO: "mx" },
    { key: "Malaysia", ISO: "my" },
    { key: "Nigeria", ISO: "ng" },
    { key: "Netherlands", ISO: "nl" },
    { key: "Norway", ISO: "no" },
    { key: "New Zealand", ISO: "nz" },
    { key: "Philippines", ISO: "ph" },
    { key: "Poland", ISO: "pl" },
    { key: "Portugal", ISO: "pt" },
    { key: "Romania", ISO: "ro" },
    { key: "Serbia", ISO: "rs" },
    { key: "Russia", ISO: "ru" },
    { key: "Saudi Arabia", ISO: "sa" },
    { key: "Sweden", ISO: "se" },
    { key: "Singapore", ISO: "sg" },
    { key: "Slovenia", ISO: "si" },
    { key: "Slovakia", ISO: "sk" },
    { key: "Thailand", ISO: "th" },
    { key: "Turkey", ISO: "tr" },
    { key: "Taiwan", ISO: "tw" },
    { key: "Ukraine", ISO: "ua" },
    { key: "United Arab Emirates", ISO: "ae" },
    { key: "United States of America", ISO: "us" },
    { key: "Venezuela", ISO: "ve" },
    { key: "South Africa", ISO: "za" },
  ]

export default countries;